---
title: Aerodynamics & Electromagnetic Simulation | Flexcompute
email: support@flexcompute.com
email_2: support@flexcompute.com
description: Flexcompute is an IT company that specializes in providing solutions
  related to simulation.
black_logo_1x: "/assets/images/logo/logo.png"
black_logo_2x: "/assets/images/logo/logo@2x.png"
black_logo_small: "/assets/images/logo/logo-small.png"
light_logo_1x: "/assets/images/logo/logo-light.png"
light_logo_2x: "/assets/images/logo/logo-light@2x.png"
light_logo_small: "/assets/images/logo/logo-small-light.png"
address_01: 130 Trapelo Rd<br>Belmont, MA 02478<br />United States
phone_number: ''
copyright_text: "© 2024 Flexcompute. All rights reserved."
flexcompute_url: 'https://www.flexcompute.com/'
contact_us_url: 'https://www.flexcompute.com/contact/'

google_map: '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3172.4564967931838!2d-122.03250858386237!3d37.33169997984258!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fb5b6e94ffe23%3A0x63bb79532baa6af4!2sApple+Campus!5e0!3m2!1sen!2str!4v1553850783971!5m2!1sen!2str"
  style="width:100%; height: 100%; border:0" allowfullscreen=""></iframe>

  '
google_reCAPTCHA:
  enable: true
  key: 6LeFvCMfAAAAAI4SClhT2s7686JCK0TIRDzk2QED
contact_us_form_id: qk2YFbfD

social_accounts:
  title: Follow Us
  links:
  - url: https://www.linkedin.com/company/flexcompute-inc
    icon: jam jam-linkedin


one_page_nav_settings:
  links:
  - text: Home
    url: "#home"
  - text: Services
    url: "#services"
  - text: Experiences
    url: "#experiences"
  - text: Portfolio
    url: "#portfolio"
  - text: Testimonials
    url: "#testimonials"
  - text: Contact
    url: "#contact"
author_page_header:
  header_background_image: ''


# Login
login:
  text: Log in
  url: javascript:void(0)
  menu_type: dropdown
  submenu:
  - text: Flow360
    url: https://client.flexcompute.com
    target: _blank
  - text: Tidy3D
    url: https://tidy3d.simulation.cloud
    target: _blank

# Contact Us
contact_us:
  text: Contact Sales
  url: /contact/
  submenu:
  - text: Email
    url: "mailto:sales@flexcompute.com"
  # - text: Locations
  #   url: /contact#locations

# Copyright settings
copyright_infos:
  - text: Terms & Conditions
    url: "/terms-of-use/"
  - text: Privacy Policy
    url: '/privacy'
  - text: Copyright © 2024 Flexcompute, Inc.
    url: 'javascript:void(0)'

# hr position
recruit_section:
  email: hr@flexcompute.com
  steer_text: 'If you’re interested in joining Flexcompute, even if your skills and background don’t fit an open position exactly, please send your application.'

terms_conditions_link: 'https://www.flexcompute.com/terms-of-use/'
privacy_link: 'https://www.flexcompute.com/privacy/'
